name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build:all
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.dmg
            build/latest-mac.yml
          draft: false
          prerelease: true
          name: "TexFlow v${{ github.ref_name }} (Beta)"
          body: |
            ## TexFlow Beta Release
            
            This is a beta version of TexFlow - LaTeX equation editor.
            
            ### Downloads
            - **Intel Mac**: TexFlow-${{ github.ref_name }}.dmg
            - **Apple Silicon**: TexFlow-${{ github.ref_name }}-arm64.dmg
            
            ### What's New
            - Initial beta release
            - Real-time LaTeX equation editing and preview
            - Monaco editor integration
            - KaTeX rendering support
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
