name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Convert icons (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run convert-icon

      - name: Convert icons (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install imagemagick -y
          if (Test-Path "img/logo.png") {
            magick img/logo.png -define icon:auto-resize=256,128,64,48,32,16 img/logo.ico
            Write-Host "Windows icon created: img/logo.ico"
          }
        shell: pwsh

      - name: Build application
        run: npm run build:all
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            build/*.dmg
            build/latest-mac.yml

      - name: Upload artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            build/*.exe
            build/latest.yml

  create-release:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-build
          path: ./macos-build

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./windows-build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./macos-build/*.dmg
            ./macos-build/latest-mac.yml
            ./windows-build/*.exe
            ./windows-build/latest.yml
          draft: false
          prerelease: true
          name: "TexFlow v${{ github.ref_name }} (Beta)"
          body: |
            ## TexFlow Beta Release
            
            This is a beta version of TexFlow - LaTeX equation editor.
            
            ### Downloads
            - **Intel Mac**: TexFlow-${{ github.ref_name }}.dmg
            - **Apple Silicon**: TexFlow-${{ github.ref_name }}-arm64.dmg
            - **Windows**: TexFlow Setup ${{ github.ref_name }}.exe
            
            ### What's New
            - Initial beta release
            - Real-time LaTeX equation editing and preview
            - Monaco editor integration
            - KaTeX rendering support
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
